### ISSUE TITLE
Mise à jour des textes de la page d'accueil

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#15]
Hello, j'ai mis à jour les textes de la page d'accueil (dans la version française uniquement) à l'endroit suivant : 
![image](https://user-images.githubusercontent.com/15101151/68211847-a5220600-ffd8-11e9-8668-2d72a2285c1e.png)
J'ai fait les pull requests, mais la page d'accueil du site ne semble pas s'être mise à jour. 
Faut-il faire quelque chose de plus ? Merci

**Comment by MattiSG** [comment]
Oui, il faut que je les valide :wink: une « pull request » est en attente jusqu'à ce qu'elle soit intégrée (« merge »).

**Comment by MattiSG** [comment]
Ah, pardon, je n'avais pas vu que tu avais déjà merge #13. Effectivement, il semble y avoir un souci. Je regarde.

**Comment by MattiSG** [comment]
Corrigé via #16, mais la cause racine n'est pas encore identifiée. J'ai vérifié la configuration de GitHub Pages, tout semble correct. Si cela se reproduit, il faudra envisager d'héberger la compilation du site nous-mêmes.
