### ISSUE TITLE
Failed check to update the subtitle on top of "Support the call" button

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#22]
Hello, j'ai voulu changer la phrase "Tous les États, entreprises et organisations peuvent s’engager" qui se trouve au-dessus des boutons "Soutenir l'appel" mais il semblerait que ce que j'ai fait ne passe pas les checks. Je voulais remplacer : 

- Français : "Tous les États, entreprises et organisations peuvent s’engager" par "États, collectivités locales, entreprises, organisations de la société civile : rejoignez-nous !"

- Anglais : "All States, companies and organisations can commit" par "States, local governments, industry, civil society organisations: join the Call!"

![image](https://user-images.githubusercontent.com/15101151/68317649-cc9dcf00-00bb-11ea-8f56-e5399779ff77.png)

**Comment by clementinede** [comment]
Je viens de tenter en ajoutant des guillemets et ça n’a pas l’air d’apparaître sur le site… J’ai fait la modif ici, ce n’est peut-être pas le bon endroit ? 
 
![image](https://user-images.githubusercontent.com/15101151/68404664-316e2d80-017f-11ea-8f2c-41bb0c70c918.png)

**Comment by MattiSG** [comment]
Ça apparaît bien sur la page « support » : https://pariscall.diplomatie.fr/fr/support  :)
Il se trouve que le texte était le même pour les rappels sur la page d'accueil, mais est configuré indépendamment dans https://github.com/ambanum/ParisCall/blob/master/_data/translations/global.yml#L7-L9.

On peut éventuellement faire en sorte que la source de donnée soit la même si c'est plus simple ; l'idée était de laisser de la flexibilité pour modifier par la suite, mais je comprends que ça puisse être confus 😕

**Comment by MattiSG** [comment]
Corrigé comme vu au tél
