### ISSUE TITLE
Nom des pays en anglais

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#26]
Les noms des pays qui soutiennent l'Appel ne sont pas traduits en anglais : 
![image](https://user-images.githubusercontent.com/15101151/68409304-215a4c00-0187-11ea-9e06-1ab10b76500f.png)
De la même façon, les noms des pays d'origine des entreprises et assos ne sont pas traduits en anglais  :
![image](https://user-images.githubusercontent.com/15101151/68409422-58306200-0187-11ea-863c-a1655490c12b.png)

Je vais vous mettre les noms de pays en français et en anglais dans le fichier Excel qui liste les soutiens si c'est le plus simple pour vous.

**Comment by MattiSG** [comment]
Je te confirme que les noms de pays sont directement pris depuis le fichier Excel, et ne sont pas localisés à ce jour. Si tu changes dans le fichier Excel, ce que tu auras indiqué sera importé à la prochaine exécution du script d'import (demain a priori), mais les données ne changeront pas dynamiquement au changement de langue.

**Comment by MattiSG** [comment]
Les pages individuelles ont été supprimées.
