### ISSUE TITLE
Link to "report an abuse" doesn't work

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#28]
Hello, le lien pour signaler un abus à la fin des deux formulaires (rejoindre le call ou proposer un événement) ne semble pas fonctionner, ni dans la version française ni anglaise.
![image](https://user-images.githubusercontent.com/15101151/68414387-633bc000-0190-11ea-925b-bfc84bea6c6c.png)

**Comment by MattiSG** [comment]
C'est un lien fourni par le service tiers Typeform, on n'est pas censé l'utiliser et on ne peut pas le réparer :wink:
