### ISSUE TITLE
Commit failed when updating legal notice on the website

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#44]
I tried to remove the name of Florian Escudié from the legal notice page on the Paris Call website, but the commit failed.

**Comment by MattiSG** [comment]
This will be fixed at the same time as #43.

However, as already discussed in November 2019, please note that the “direction de rédaction” mention (including the name of the individual) is a [legal obligation](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31228) in France. You should thus update the name if has changed, but not remove the paragraph.

**Comment by MattiSG** [comment]
Fixed in #45.
