### ISSUE TITLE
Absence d'article dans la description détaillée des soutiens

### ISSUE THREAD

**Issue by clementinede** [ambanum/pariscall.international#7]
Si je vais sur https://pariscall.diplomatie.fr/fr/supporter/trendmicro/
Je vois le texte "Entreprise Trendmicro soutient l’Appel de Paris..."
Et je voudrais voir le texte "L'entreprise Trend..."

A choisir, je préfère encore ne pas avoir le type de soutien que de le voir écrit comme ça :wink:

**Comment by MattiSG** [comment]
Les pages individuelles des soutiens ont été supprimées.
